version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_crud
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  # Uncomment below to run the NestJS app in Docker as well
  # app:
  #   build: .
  #   command: npm run start:dev
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_NAME=customer_crud
  #   depends_on:
  #     - db

volumes:
  db_data: